export const ERROR_CODE = {
  VALIDATION_EXCEPTION: 'VALIDATION_EXCEPTION',
  INTERNAL_EXCEPTION: 'INTERNAL_EXCEPTION',
  DUPLICATE_EXCEPTION: 'DUPLICATE_EXCEPTION',
  BASE_EXCEPTION: 'BASE_EXCEPTION',
  PASSWORD_MISMATCH_EXCEPTION: 'PASSWORD_MISMATCH_EXCEPTION',
  NOT_FOUND_EXCEPTION: 'NOT_FOUND_EXCEPTION',
  UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
} as const;
