services:
  postgresql:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ../.env.dev
    ports:
      - '15432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - hh-study

networks:
  hh-study:
    driver: bridge
