export const ERROR_CODE = {
  VALIDATION_EXCEPTION: 'VALIDATION_EXCEPTION',
  INTERNAL_EXCEPTION: 'INTERNAL_EXCEPTION',
  DUPLICATE_EXCEPTION: 'DUPLICATE_EXCEPTION',
  BASE_EXCEPTION: 'BASE_EXCEPTION',
} as const;
